SHELL = /bin/sh
CXX=clang2++

SRCDIR = ./src
SOURCES = $(shell find $(SRCDIR) -type f -name *.cpp)
HEADERS = $(shell find $(SRCDIR) -type f -name *.h) $(shell find ../external/glm -type f -name *.hpp)
OBJECTS = $(SOURCES:.cpp=.o)
CXXFLAGS = -I $(SRCDIR)/core -I $(SRCDIR)/geom -I $(SRCDIR)/io -I ../external/glm -fopenmp -Wall -v -stdlib=libstdc++
EXEC = ./bin/cariboupt
LDFLAGS = -lm 

all: $(EXEC)

clean:
	find $(SRCDIR) -type f -name *.o -delete
	rm $(EXEC)

%.o: %.c $(HEADERS)
	$(CXX) $(CXXFLAGS) -c $@ $<

$(EXEC) : $(OBJECTS)
	$(CXX) $(CXXFLAGS) $(OBJECTS) -o $(EXEC)

.cpp:
	$(CXX) $(CXXFLAGS) -c $@